name: Adorn CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --no-scripts
      - run: npm run bootstrap
      - run: npm run run emit
      - run: npm run run build
      - run: npm run run lint
      - uses: actions/upload-artifact@v3
        with:
          path: |
            packages/annotate/build
            packages/annotate/package.json
            packages/annotate/package-lock.json
            packages/annotate/README.md

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --no-scripts
      - run: npm run bootstrap
      - run: npm run run test:ci

  bump:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, '[RELEASE]')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: fregante/setup-git-user@v1
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push

  release:
    needs: test
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, '[RELEASE]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: .
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm version patch
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ADORN }}
