name: Adorn CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildAndTest:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --no-scripts
      - run: npm run bootstrap
      - run: npm run run emit
      - run: npm run run build
      - run: npm run run lint
      - run: npm run run test:ci

  bump:
    if: github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, '[RELEASE]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: fregante/setup-git-user@v1
      - run: |
          npm run release:patch
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildForRelease:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --no-scripts
      - run: npm run bootstrap
      - run: npm run run emit
      - run: npm run run build --scope annotate
      - uses: actions/upload-artifact@v3
        with:
          path: |
            packages/annotate/build
            packages/annotate/package.json
            packages/annotate/package-lock.json
            packages/annotate/README.md

  release:
    needs: buildForRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: .
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ADORN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
